### ISSUE TITLE
Api rate limit attributes should be int, not str

### ISSUE THREAD

**Issue by jdagilliland** [sbg/sevenbridges-python#5]
I stumbled across this while trying to prevent a script from bumping up against the rate limit all the time, but the rate limit attributes (which are fundamentally integral in nature) should in fact be integers.

I happened to be just plainly comparing them to an `int`, to see if I had enough requests remaining, but the `str`s were always comparing greater than or equal to `n`.

**Comment by delicb** [comment]
Hi @jdagilliland.

Thanks for the report. You are right, we should fix this. 

As far as I can tell, library only stores values returned from server in headers, which are always strings, without any processing. So, properties `limit` and `remaining` should be converted to int and `reset_time` should be `datetime` object to be useful.

It will be fixed in next release. For now, I guess you can, as workaround, convert value yourself (`int(api.limit)` should suffice and will not break once we fix this).

**Comment by SenadI** [comment]
Fixed in Release 0.3.0
