### ISSUE TITLE
Would be nice if files.query(names=[ ... ]) maintained query order

### ISSUE THREAD

**Issue by kghosesbg** [sbg/sevenbridges-python#51]
Currently when a list of file names is passed into the query function the returned order is not related to the list of file names supplied. In many cases it would be very useful to have this ordering. Thanks!

**Comment by SenadI** [comment]
@kghosesbg This can not be done because neither the server can guarantee the ordering, and also python lib holds the resource in a normal dictionary and as you know it does not keep ordering. Therefore a clever trick would have to be introduced in the lib code itself which is I think is currently not worth doing. If a need in the future appears I will revisit this ticket.
