### ISSUE TITLE
Make file objects comparable

### ISSUE THREAD

**Issue by bjoernpollex** [sbg/sevenbridges-python#6]
Currently file objects cannot be compared in a meaningful way. Example:

```python
>>> api.files.get(id='asdf') == api.files.get(id='asdf')
False
```
It is possible to compare them by their `id` attribute, but that becomes difficult when comparing lists of files.

**Comment by SenadI** [comment]
Hi @bjoernpollex we opted out of overriding the `__equals__` method because of many reasons. But you have available `equals()` method on all resources and you can use it.

```python
>>> api.files.get(id='asdf').equals(api.files.get(id='asdf'))
True
```
This method will basically compare if the object types are equal and the corresponding API JSON objects are identical. Hope you find this method sufficient for your usecase.

**Comment by SenadI** [comment]
Yes that is correct. There are many different ways to do it pythonic wise, one liners and similar but it does not the change the state of the problem you just described. Let me leave this open for now and will take a closer look.

**Comment by SenadI** [comment]
We will not do this soon. If the need for it arrises again, we can revisit the issue.
