### ISSUE TITLE
Issue with generator during querying

### ISSUE THREAD

**Issue by jorda90** [sbg/sevenbridges-python#83]
When a user queries (ex. files) and uses `.all()` method to produce a generator and then modifies elements during iteration not all paginated pages are transversed. I am usually left with 50 items ( a single default page) that is skipped. If `list(.all())` is used and generator is casted into list all work fine.

**Comment by SenadI** [comment]
@jorda90 and myself debugged this and its not an error with the library. Users should not modify the resources while using .all() method. If the resources are modified during iteration so are the `href` properties of the collection which looks like API server is yielding wrong values and eventually it does not paginate to completion (ie. user is left with 50, 100 or some `n`) number of values.

**Comment by mattions** [comment]
@SenadI this is very dangerous. 
We expect a user to modify the resources using the `.all()` method, because the user wants to iterate all the objects without dealing with the pagination themself.

I think it's important to make sure this is possible, otherwise we will have a lot of users which will get a lot of error.


Is there a way to implment the `.all()` so the objects returned can be modified?

**Comment by SenadI** [comment]
This is not related to simple queries. It is related when for example you are searching for files with specific tags and removing that exact tag when iterating.... It makes no sense to do that `list(.all())` gets you your local copy of the files where you can do whatever you like.

**Comment by mattions** [comment]
ah ok! That makes sense then :+1:
